//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string FullDes { get; set; }
        public Nullable<decimal> PriceStarting { get; set; }
        public Nullable<decimal> PriceBuy { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<decimal> PriceHighest { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<bool> Adjourning { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<decimal> Step { get; set; }
        public Nullable<int> Seller { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceCurrent { get; set; }
    }
}
